name=ESP8266AIGemini
version=1.0.4
author=Oscar Gonzalez
maintainer=Oscar Gonzalez <oigonzalezp2024@gmail.com>
sentence=Gemini Client for ESP8266.
paragraph=Enables the ESP8266 to connect to the Google Gemini API using a decoupled and modular implementation (Hexagonal Architecture/Ports & Adapters). Includes network logic, validation, and JSON parsing.
category=Communication
url=https://github.com/oigonzalezp2024/ESP8266AIGemini
architectures=esp8266
license=MIT
keywords=gemini, google, ai, artificial intelligence, esp, esp8266, hexagonal, ports, adapters, communication, json, http, networking, lwip
